before_script:
  - npm i -g eslint
  - eslint .

language: node_js

node_js:
  - 8
  - 10
  - 12
  - 13

notifications:
  slack:
    rooms:
      - secure: "SOyb1L7KTf/NxLj+lunFnq4UJxXVIHHwFdPwIe4c3VbBZOeUR/0x+b2swNgJ+/rnra0Th+RCZTZ99LrBGpFchFI6hYXjLVdGGL8LhyfUuREG2tW7/MsQfTQuZwqqc6cc0trn4VGSJYVHDW428XUPc3VIJyrV1KP8NBsmMl499AY="
    on_success: always

script:
  - npm run coveralls